version: '3.8'

volumes:
  database: {}

services:
  database:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - MARIADB_VERSION=10.7.1
    restart: unless-stopped
    volumes:
      - database:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=database
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    #ports:
    #  - 127.0.0.1:3306:3306/tcp
