version: '3.4'

volumes:
  database: {}

services:
  database:
    build:
      dockerfile: Dockerfile
      context: .
    restart: unless-stopped
    volumes:
      - database:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    #ports:
    #  - 127.0.0.1:3306:3306/tcp
