version: '3'

volumes:
  database: {}

services:
  database:
    image: ghcr.io/richardds/mariadb:10.6-A
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - MARIADB_VERSION=10.6
    restart: unless-stopped
    volumes:
      - database:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    ports:
      - 127.0.0.1:3306:3306/tcp
