name: Docker

on:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          mariadb_version: ['10.6', '10.7', '10.8', '10.9', '10.10']
    steps:
      -
        name: Setup Docker
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          build-args: |
            MARIADB_VERSION=${{ matrix.mariadb_version }}
          push: true
          tags: |
            richardboldis/mariadb:latest
            richardboldis/mariadb:${{ matrix.mariadb_version }}-${{ github.ref_name }}
            ghcr.io/richardds/mariadb:latest
            ghcr.io/richardds/mariadb:${{ matrix.mariadb_version }}-${{ github.ref_name }}
